version: "3.8"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  consul:
    image: consul
    ports:
      - "8500:8500"
  apigateway:
    build: ./api-gateway
    image: phi180/api-gateway
    environment:
      - SPRING_PROFILE=default
    ports:
      - "8080:8080"
    depends_on:
      - "consul"
  enigmi:
    build: ./enigmi
    image: phi180/enigmi
    environment:
      - SPRING_PROFILE=default
    depends_on:
      - "consul"
  enigmidb:
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enigmidb
    depends_on:
      - "consul"
  connessioni:
    build: ./connessioni
    image: phi180/connessioni
    environment:
      - SPRING_PROFILE=default
    depends_on:
      - "consul"
  connessionidb:
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: connessionidb
    depends_on:
      - "consul"
  enigmi-seguiti:
    build: ./enigmi-seguiti
    image: phi180/enigmi-seguiti
    environment:
      - SPRING_PROFILE=default
    depends_on:
      - "consul"
  enigmiseguitidb:
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enigmiseguitidb
    depends_on:
      - "consul"
  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      #      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.11.121:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock